name: Maven Build and Test

on:
  push:
    branches:
      - main  # ou la branche sur laquelle vous souhaitez exécuter l'action
  pull_request:
    branches:
      - main  # ou la branche sur laquelle vous souhaitez exécuter l'action

jobs:
  build:
    runs-on: ubuntu-latest  # Utilise une image Ubuntu

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Permet de récupérer le code source du dépôt

      - name: Build project with Maven in Docker
        uses: addnab/docker-run-action@v3  # Utilise une action pour exécuter un container Docker
        with:
          image: maven:3.8.1-jdk-11-openj9  # L'image Docker que vous avez mentionnée
          options: --rm  # Supprime le container après l'exécution
          run: mvn package -DskipTests  # Exécute la commande Maven dans le container Docker

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3  # Mise à jour vers la version v3
        with:
          name: build-artifacts  # Nom des artefacts
          path: target/  # Chemin vers le répertoire contenant les artefacts à sauvegarder

  test:
    runs-on: ubuntu-latest  # Utilise une image Ubuntu

    needs: build  # Dépend de l'étape de build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Récupère le code source

      - name: Download build artifacts
        uses: actions/download-artifact@v3  # Mise à jour vers la version v3
        with:
          name: build-artifacts  # Le nom des artefacts à récupérer
          path: target/  # Dossier où les artefacts seront téléchargés

      - name: Run tests in Docker
        uses: addnab/docker-run-action@v3  # Utilise une action pour exécuter un container Docker
        with:
          image: maven:3.8.1-jdk-11-openj9  # L'image Docker
          options: --rm  # Supprime le container après l'exécution
          run: mvn test -DlastModGranularityMs=10000000  # Exécute les tests Maven dans le container Docker
